---
schema:
  procedures: {}
  tables:
    category:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - category_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - name
          match_type: ''
          name: uniq_category
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
      fields:
        category_id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: category_id
          order: 1
          size:
            - 0
        name:
          data_type: varchar
          default_value: ~
          extra:
            COLLATE: utf8_bin
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: name
          order: 2
          size:
            - 50
      indices: []
      name: category
      options: []
      order: 1
    item:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - item_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - item_id
            - category_fk
          match_type: ''
          name: item_category_uniq
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
        - deferrable: 1
          expression: ''
          fields:
            - category_fk
          match_type: ''
          name: item_fk_category_fk
          on_delete: ''
          on_update: ''
          options: []
          reference_fields:
            - category_id
          reference_table: category
          type: FOREIGN KEY
      fields:
        category_fk:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: category_fk
          order: 2
          size:
            - 0
        item_id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 1
          name: item_id
          order: 1
          size:
            - 0
        name:
          data_type: varchar
          default_value: ~
          extra:
            COLLATE: utf8_bin
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: name
          order: 3
          size:
            - 96
      indices:
        - fields:
            - category_fk
          name: item_idx_category_fk
          options: []
          type: NORMAL
      name: item
      options: []
      order: 3
    item_tag:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - item_tag_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - item_fk
            - tag_fk
          match_type: ''
          name: item_tag_uniq
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
        - deferrable: 1
          expression: ''
          fields:
            - item_fk
          match_type: ''
          name: item_tag_fk_item_fk
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - item_id
          reference_table: item
          type: FOREIGN KEY
        - deferrable: 1
          expression: ''
          fields:
            - tag_fk
          match_type: ''
          name: item_tag_fk_tag_fk
          on_delete: ''
          on_update: ''
          options: []
          reference_fields:
            - tag_id
          reference_table: tag
          type: FOREIGN KEY
      fields:
        item_fk:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: item_fk
          order: 2
          size:
            - 0
        item_tag_id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: item_tag_id
          order: 1
          size:
            - 0
        tag_fk:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: tag_fk
          order: 3
          size:
            - 0
      indices:
        - fields:
            - item_fk
          name: item_tag_idx_item_fk
          options: []
          type: NORMAL
        - fields:
            - tag_fk
          name: item_tag_idx_tag_fk
          options: []
          type: NORMAL
      name: item_tag
      options: []
      order: 4
    tag:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - tag_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - name
          match_type: ''
          name: uniq_tag_name
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
      fields:
        name:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: name
          order: 2
          size:
            - 0
        tag_id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: tag_id
          order: 1
          size:
            - 0
      indices: []
      name: tag
      options: []
      order: 2
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    sources:
      - Category
      - Item
      - ItemTag
      - Tag
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 0.11020
