requires 'DBI';
requires 'DBIx::Class';
requires 'JSON';
requires 'Mojolicious';
requires 'Test::Most';
requires 'Text::CSV';
requires 'Try::Tiny';
requires 'YAML';
requires 'DateTime::Format::MySQL';
requires 'DateTime';
requires 'Log::Any';
requires 'List::MoreUtils';
requires 'Plack';
requires 'Starman';
requires 'Moose';

#### Testing
requires 'Class::Mockable';
test_requires 'Test::MockObject';
test_requires 'LWP::UserAgent::Mockable';
